spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/thanh_angular_spring
    username: postgres
    password: thanhkon123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSLDialect
  mail:
    host: localhost
      port: 1025
    username: thanh
    password: thanh123
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true