version: '3.8'
services:
  postgres:
    container_name: postgres-sql-bsn
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: thanhkon123
      PGDATA: /var/lib/postgresql/data  # Corrected path
      POSTGRES_DB: book_social_network
    volumes:
      - postgres:/var/lib/postgresql/data  # Corrected volume path
    ports:
      - "5432:5432"
    networks:
      - spring-angular
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"
      - "1025:1025"
    networks:
      - spring-angular  # Added this to include mail-dev in the same network

networks:
  spring-angular:  # Properly moved to the top level
    driver: bridge

volumes:
  postgres:
    driver: local
